import { db } from './db';

let schemaPromise: Promise<void> | undefined;

/** Creates the PostgreSQL schema once per warm function instance. */
export function initSchema(): Promise<void> {
  schemaPromise ??= db.exec(`
    CREATE TABLE IF NOT EXISTS settings (key TEXT PRIMARY KEY, value TEXT NOT NULL);
    CREATE TABLE IF NOT EXISTS categories (key TEXT PRIMARY KEY, name_en TEXT NOT NULL, name_ar TEXT NOT NULL, color TEXT NOT NULL);
    CREATE TABLE IF NOT EXISTS people (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name TEXT NOT NULL UNIQUE, type TEXT NOT NULL DEFAULT 'owe', note TEXT, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
    CREATE TABLE IF NOT EXISTS transactions (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, date TEXT NOT NULL, merchant TEXT NOT NULL, category TEXT NOT NULL,
      method TEXT, account_id INTEGER, original_currency TEXT NOT NULL DEFAULT 'USD', original_amount DOUBLE PRECISION NOT NULL,
      converted_amount DOUBLE PRECISION NOT NULL, type TEXT DEFAULT 'spend', note TEXT, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      salary_id TEXT
    );
    CREATE TABLE IF NOT EXISTS salaries (
      id TEXT PRIMARY KEY, company TEXT NOT NULL, role TEXT, gross DOUBLE PRECISION, net DOUBLE PRECISION NOT NULL,
      payday TEXT, type TEXT, date TEXT, currency TEXT DEFAULT 'USD', month INTEGER NOT NULL, year INTEGER NOT NULL,
      method TEXT DEFAULT 'Salary', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );
    CREATE TABLE IF NOT EXISTS services (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name TEXT NOT NULL, description TEXT, terms TEXT, amount DOUBLE PRECISION NOT NULL,
      status TEXT DEFAULT 'Active', next_invoice TEXT, date TEXT, currency TEXT DEFAULT 'USD', month INTEGER NOT NULL, year INTEGER NOT NULL
    );
    CREATE TABLE IF NOT EXISTS subscriptions (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name TEXT NOT NULL, plan TEXT, cost DOUBLE PRECISION NOT NULL,
      next_billing TEXT, date TEXT, currency TEXT DEFAULT 'USD', month INTEGER NOT NULL, year INTEGER NOT NULL
    );
    CREATE TABLE IF NOT EXISTS bills (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name TEXT NOT NULL, cost DOUBLE PRECISION NOT NULL, average DOUBLE PRECISION,
      date TEXT, currency TEXT DEFAULT 'USD', month INTEGER NOT NULL, year INTEGER NOT NULL
    );
    CREATE TABLE IF NOT EXISTS debts (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, person TEXT NOT NULL, type TEXT NOT NULL DEFAULT 'owe',
      total DOUBLE PRECISION NOT NULL, remaining DOUBLE PRECISION NOT NULL, due TEXT, date TEXT, note TEXT, currency TEXT DEFAULT 'USD', status TEXT DEFAULT 'active', month INTEGER NOT NULL, year INTEGER NOT NULL
    );
    CREATE TABLE IF NOT EXISTS budgets (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, category_key TEXT NOT NULL, budget_amount DOUBLE PRECISION NOT NULL,
      month INTEGER NOT NULL, year INTEGER NOT NULL, currency TEXT DEFAULT 'USD'
    );
    CREATE TABLE IF NOT EXISTS recurring_transactions (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, type TEXT NOT NULL DEFAULT 'spend', category TEXT NOT NULL,
      method TEXT, account_id INTEGER, merchant TEXT NOT NULL, original_currency TEXT DEFAULT 'USD',
      original_amount DOUBLE PRECISION NOT NULL, note TEXT, frequency TEXT NOT NULL DEFAULT 'monthly',
      start_date TEXT, end_date TEXT, next_occurrence TEXT, last_generated_at TEXT, active INTEGER DEFAULT 1, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );
    CREATE TABLE IF NOT EXISTS transaction_templates (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name TEXT NOT NULL, type TEXT NOT NULL DEFAULT 'spend',
      category TEXT NOT NULL, method TEXT, account_id INTEGER, merchant TEXT NOT NULL, original_currency TEXT DEFAULT 'USD', original_amount DOUBLE PRECISION NOT NULL, note TEXT,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );
    CREATE TABLE IF NOT EXISTS payment_methods (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name TEXT NOT NULL, type TEXT NOT NULL DEFAULT 'card', details TEXT, icon TEXT, network TEXT, last4 TEXT, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );
    CREATE TABLE IF NOT EXISTS accounts (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name TEXT NOT NULL, type TEXT NOT NULL DEFAULT 'bank', currency TEXT NOT NULL DEFAULT 'USD',
      details TEXT, icon TEXT, balance DOUBLE PRECISION DEFAULT 0, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );
    CREATE TABLE IF NOT EXISTS merchants (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name TEXT NOT NULL UNIQUE, category TEXT, osm_id TEXT, osm_type TEXT, address TEXT,
      latitude DOUBLE PRECISION, longitude DOUBLE PRECISION, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );
    CREATE TABLE IF NOT EXISTS external_cache (
      provider TEXT NOT NULL, cache_key TEXT NOT NULL, payload TEXT NOT NULL, fetched_at TEXT NOT NULL, expires_at TEXT NOT NULL,
      PRIMARY KEY (provider, cache_key)
    );
    CREATE TABLE IF NOT EXISTS purchase_candidates (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, source TEXT NOT NULL, external_id TEXT NOT NULL, merchant TEXT, purchase_date TEXT,
      amount DOUBLE PRECISION, currency TEXT, card_last4 TEXT, matched_method_id INTEGER, category TEXT, note TEXT, confidence DOUBLE PRECISION DEFAULT 0,
      raw_text TEXT, place_id TEXT, latitude DOUBLE PRECISION, longitude DOUBLE PRECISION, status TEXT DEFAULT 'pending', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      UNIQUE(source, external_id)
    );
    CREATE INDEX IF NOT EXISTS idx_transactions_date ON transactions(date);
    CREATE INDEX IF NOT EXISTS idx_transactions_category ON transactions(category);
    CREATE INDEX IF NOT EXISTS idx_transactions_type ON transactions(type);
    CREATE INDEX IF NOT EXISTS idx_transactions_salary_id ON transactions(salary_id);
    CREATE INDEX IF NOT EXISTS idx_transactions_account_id ON transactions(account_id);
    CREATE INDEX IF NOT EXISTS idx_recurring_transactions_next_occurrence ON recurring_transactions(next_occurrence);
    CREATE INDEX IF NOT EXISTS idx_recurring_transactions_active ON recurring_transactions(active);
    CREATE INDEX IF NOT EXISTS idx_purchase_candidates_source_external ON purchase_candidates(source, external_id);
    CREATE INDEX IF NOT EXISTS idx_purchase_candidates_status ON purchase_candidates(status);
  `);
  return schemaPromise;
}
